version: '3.7'

volumes:
  app_database:
  app_cache: {}

networks:
  utente_ddd_net:
    driver: bridge
    name: utente_ddd_net

services:
  web:
    image: nginx:latest
    depends_on:
      - php_ddd_utente
    volumes:
      - ../:/var/www/app
      - ./nginx/symfony-4.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx
    networks:
      - utente_ddd_net

  php_ddd_utente:
    build: php
    hostname: app_hostname
    volumes:
      - ../:/var/www/app
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - utente_ddd_net
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history

  servicedb:
    image: mariadb:10.4.7-bionic
    volumes:
      - app_database:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ddd_utente
    #command: mysqld --sql_mode="" #Per mysql, non serve per mariadb
    networks:
      - utente_ddd_net

  #  phpmyadmin:
  #    image: phpmyadmin/phpmyadmin
  #    depends_on:
  #      - servicedb
  #    environment:
  #      - PMA_HOST=servicedb
  #    networks:
  #      - utente_ddd_net

  servicememcached:
    image: memcached:latest
    volumes:
      - app_cache:/var/lib/memcached
    networks:
      - utente_ddd_net
