signup_utente:
  path: /utente
  methods: [POST]
  controller: UtenteDDD\Utente\Infrastructure\Communication\Http\Symfony\Controller\UtenteController::registraUtente
  requirements:
    _format: json|html
