UtenteDDD\Utente\Domain\Aggregate\Utente:
  type: entity
  table: utenti
  id:
    idUtente:
      type: IdUtente
      column: id

  manyToMany:
    competenze:
      orphanRemoval: true
      cascade: ["all"]
      targetEntity: UtenteDDD\Utente\Domain\Aggregate\Competenza
      joinTable:
        name: competenze_utente
      joinColumns:
        utente_id:
          referencedColumnName: id
      inversedJoinColumns:
        competenza_id:
          referencedColumnName: id
          unique: true

  fields:
    email:
      type: EmailUtente
      nullable: false
    password:
      type: HashedPassword
      nullable: false
    ruolo:
      type: Ruolo
      nullable: false
    enabled:
      type: boolean
      nullable: false
    locked:
      type: boolean
      nullable: false
