services:
  _defaults:
    autowire: true
    autoconfigure: true

  UtenteDDD\Utente\Application\Service\RegistraUtenteFromRequest:
    arguments:
      $dataTransformer: '@UtenteDDD\Utente\Application\DataTransformer\UtenteArrayDataTransformer'
