parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  UtenteDDD\Utente\Infrastructure\Communication\Http\Symfony\Controller\:
    resource: '%kernel.project_dir%/src/UtenteDDD/Utente/Infrastructure/Communication/Http/Symfony/Controller/*'
    tags: ['controller.service_arguments']


