services:
  _defaults:
    autowire: true
    autoconfigure: true

  UtenteDDD\Utente\Application\DataTransformer\:
    resource: '%kernel.project_dir%/src/UtenteDDD/Utente/Application/DataTransformer/*'
