services:
  _defaults:
    autowire: true
    autoconfigure: true

  UtenteDDD\Utente\Domain\Service\:
    resource: '%kernel.project_dir%/src/UtenteDDD/Utente/Domain/Service/*'

  UtenteDDD\Utente\Domain\Service\PasswordHashing:
    class: UtenteDDD\Utente\Infrastructure\Domain\Service\BasicPasswordHashing
