services:
  _defaults:
    autowire: true
    autoconfigure: true

  UtenteDDD\Utente\Infrastructure\Domain\Service\:
    resource: '%kernel.project_dir%/src/UtenteDDD/Utente/Infrastructure/Domain/Service/*'
