services:
  _defaults:
    autowire: true
    autoconfigure: true

  UtenteDDD\Utente\Domain\Aggregate\Utenti:
    class: UtenteDDD\Utente\Infrastructure\Domain\Aggregate\Doctrine\DoctrineUtenti
    arguments:
      - '@doctrine'
      - 'UtenteDDD\Utente\Domain\Aggregate\Utente'
